name: Deploy Laravel to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3


      - name: Sync files with InfinityFree FTPss
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_42620973
          password: Limonium2026
          server-dir: /htdocs/
          exclude: |
            .git**
            .github**
            node_modules/**
            vendor/**
            tests/**
            storage/*.sqlite
            .env
            .env.example
            README.md
